#!/bin/bash
# =============================================================================
# get-host-apk-tools.sh — obtain an apk-tools 3 binary that HAS `mkndx`
# =============================================================================
#
# MEASURED FACT (2026-09-13): the apk shipped in an OpenWrt 25.12 TARGET rootfs
# has no `mkndx` subcommand — its command list is add/del/fix/update/upgrade/
# cache/query/list/dot/policy/search/info/fetch/manifest/extract/verify/audit/
# stats/version/adbdump. Index creation lives in the BUILD-HOST build of
# apk-tools (OpenWrt's tools/apk), which the SDK installs at
# staging_dir/host/bin/apk. This script extracts that pair (the `apk` wrapper
# plus `.apk.bin`) into a portable directory and replaces the SDK's own loader
# shim with one that runs the (statically-linked) binary directly, so it works
# on any glibc x86_64 host.
#
# Usage:
#   get-host-apk-tools.sh [--out DIR] [--image IMG | --sdk-dir DIR] [--force]
#
#   --image IMG    docker image to extract from
#                  (default openwrt/sdk:x86-64-v25.12.5 — a PINNED release image)
#   --sdk-dir DIR  an already-extracted SDK tree containing staging_dir/host/bin
#
# Result: <out>/apk  — pass it as --apk-bin to feed-publish.sh
#                     — or export FEED_APK_BIN=<out>/apk
# =============================================================================
set -euo pipefail

OUT=""
IMAGE=openwrt/sdk:x86-64-v25.12.5
SDK_DIR=""
FORCE=0

while [ $# -gt 0 ]; do
	case "$1" in
		--out)     OUT=${2:?}; shift 2 ;;
		--image)   IMAGE=${2:?}; shift 2 ;;
		--sdk-dir) SDK_DIR=${2:?}; shift 2 ;;
		--force)   FORCE=1; shift ;;
		-h|--help) sed -n '3,28p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*) echo "unknown argument: $1" >&2; exit 1 ;;
	esac
done

[ -n "$OUT" ] || OUT="$PWD/.feed-tools/apk"
mkdir -p "$OUT/bin" "$OUT/lib"
OUT=$(cd "$OUT" && pwd)

copy_from_dir() { # <sdk-root>
	local src=$1/staging_dir/host
	[ -f "$src/bin/apk" ] || { echo "FAIL: $src/bin/apk not found" >&2; return 1; }
	cp -f "$src/bin/apk" "$OUT/bin/apk"
	cp -f "$src/bin/.apk.bin" "$OUT/bin/.apk.bin"
	[ -f "$src/lib/runas.so" ] && cp -f "$src/lib/runas.so" "$OUT/lib/runas.so" || true
}

if [ -n "$SDK_DIR" ]; then
	copy_from_dir "$SDK_DIR"
else
	command -v docker >/dev/null 2>&1 || {
		echo "FAIL: neither --sdk-dir nor docker is available — extract an SDK tree first." >&2
		exit 1
	}
	echo "==> pulling $IMAGE (skipped if present)"
	docker image inspect "$IMAGE" >/dev/null 2>&1 || docker pull "$IMAGE" >&2
	cid=$(docker create "$IMAGE" true)
	trap 'docker rm -f "$cid" >/dev/null 2>&1 || true' EXIT
	# Fail loudly if the image has no host apk-tools at the expected path.
	docker cp "$cid:/builder/staging_dir/host/bin/apk" "$OUT/bin/apk" >&2
	docker cp "$cid:/builder/staging_dir/host/bin/.apk.bin" "$OUT/bin/.apk.bin" >&2
	docker cp "$cid:/builder/staging_dir/host/lib/runas.so" "$OUT/lib/runas.so" >&2 || true
	docker rm -f "$cid" >/dev/null 2>&1 || true
	trap - EXIT
fi

chmod +x "$OUT/bin/apk" "$OUT/bin/.apk.bin"

# Replace the SDK's loader shim: the binary only needs the host libc, and the
# SDK's bundled ld-linux cannot find the host's libpthread.
cat > "$OUT/bin/apk" <<'SHIM'
#!/bin/sh
# Generated by get-host-apk-tools.sh — runs the OpenWrt host apk-tools binary.
dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
exec "$dir/.apk.bin" "$@"
SHIM
chmod +x "$OUT/bin/apk"

"$OUT/bin/apk" --version
# `apk mkndx --help` exits 1 in this build — probe the text, not the status.
probe=$("$OUT/bin/apk" mkndx --help 2>&1 || true)
printf '%s' "$probe" | grep -q '^Usage: apk mkndx' \
	|| { echo "FAIL: the extracted binary has no mkndx subcommand" >&2; exit 1; }

echo "OK: $OUT/bin/apk  (has mkndx; also adbdump, mkpkg, adbsign)"
echo "export FEED_APK_BIN=$OUT/bin/apk"
